name: 230Z-env
channels:
  - conda-forge
dependencies:

  # The Works
  - python
  - numpy
  - pandas
  - matplotlib
  - ipykernel

  # Web Scraping
  - beautifulsoup4
  - requests

  # Finance Data
  - yfinance
  - alpha_vantage

  # Machine Learning
  - tensorflow
  - tensorflow-hub
  - pytorch::pytorch
  - scikit-learn
  - pmdarima
  - nltk

  # Secrets
  - python-dotenv

  - pip
  - pip:
    - stockstats
    - pytorch-pretrained-bert